# Generated by Django 6.0 on 2026-01-07 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0006_userdetails_body_fat_userdetails_cuisine_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField()),
                ("calories", models.IntegerField(editable=False)),
                ("protein_g", models.IntegerField(editable=False)),
                ("carbs_g", models.IntegerField(editable=False)),
                ("fats_g", models.IntegerField(editable=False)),
                ("is_locked", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "daily_plan",
                "ordering": ["day"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Snack", "Snack"),
                            ("Dinner", "Dinner"),
                            ("Appetizer", "Appetizer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("calories", models.IntegerField(editable=False)),
                ("protein_g", models.IntegerField(editable=False)),
                ("carbs_g", models.IntegerField(editable=False)),
                ("fats_g", models.IntegerField(editable=False)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "daily_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="meal_planner.dailyplan",
                    ),
                ),
            ],
            options={
                "db_table": "meal",
                "ordering": ["meal_type"],
            },
        ),
        migrations.CreateModel(
            name="MealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        default=1.0, help_text="Multiplier of serving size"
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.food"
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meal_planner.meal",
                    ),
                ),
            ],
            options={
                "db_table": "meal_item",
            },
        ),
        migrations.CreateModel(
            name="WeeklyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("rule", "Rule"), ("ml", "ML"), ("manual", "Manual")],
                        default="rule",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("target_calories", models.IntegerField(editable=False)),
                ("target_protein_g", models.IntegerField(editable=False)),
                ("target_carbs_g", models.IntegerField(editable=False)),
                ("target_fats_g", models.IntegerField(editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weekly_plan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="dailyplan",
            name="weekly_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="meal_planner.weeklyplan",
            ),
        ),
    ]
