# Generated by Django 6.0 on 2025-12-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='activity_level',
            field=models.CharField(default='moderate', max_length=20, null=True),
        ),
    ]
