# Generated by Django 6.0 on 2025-12-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userdetails_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='onboarding_step',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
