# Generated by Django 6.0 on 2025-12-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdetails_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='activity_level',
            field=models.CharField(default='moderate', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='allergies',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='exercise',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='food_preference',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='goal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
