# Generated by Django 6.0 on 2025-12-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userdetails_activity_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.JSONField(blank=True, default=list)),
                ('type', models.JSONField(blank=True, default=list)),
                ('category', models.JSONField(blank=True, default=list)),
                ('allergy', models.JSONField(blank=True, default=list)),
                ('serving', models.CharField(blank=True, max_length=255, null=True)),
                ('total_weight_g', models.FloatField(blank=True, null=True)),
                ('energy_kcal', models.FloatField(blank=True, null=True)),
                ('proteins_g', models.FloatField(blank=True, null=True)),
                ('carbohydrates_g', models.FloatField(blank=True, null=True)),
                ('fats_g', models.FloatField(blank=True, null=True)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('carbon_footprint_kg', models.FloatField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
