# Generated by Django 6.0 on 2026-01-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="body_fat",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="cuisine",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="meals_per_day",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="snacking",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="workout_frequency",
            field=models.IntegerField(null=True),
        ),
    ]
