# Generated by Django 5.2.9 on 2025-12-15 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("weight_kg", models.FloatField()),
                ("height_cm", models.FloatField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "activity_level",
                    models.FloatField(
                        choices=[
                            (1.2, "Sedentary"),
                            (1.375, "Lightly Active"),
                            (1.55, "Moderately Active"),
                            (1.725, "Very Active"),
                        ]
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("LOSE", "Weight Loss"),
                            ("GAIN", "Weight Gain"),
                            ("MAINTAIN", "Maintenance"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("allergies", models.JSONField(default=list)),
                (
                    "cuisine_preference",
                    models.CharField(default="Indian", max_length=50),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
