# Generated by Django 5.2.9 on 2025-12-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("calories", models.FloatField()),
                ("protein_g", models.FloatField()),
                ("carbs_g", models.FloatField()),
                ("fats_g", models.FloatField()),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("contains_nuts", models.BooleanField(default=False)),
                ("cuisine", models.CharField(max_length=50)),
                ("meal_type", models.CharField(max_length=20)),
            ],
        ),
    ]
